### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by rpesciotta** [spencercarli/meteor-cordova-photolibrary#1]
Hi,

Tried to run it for the first time, but get stuck here:

meteor-cordova-photolibrary> meteor run ios
   Installing Cordova plugins                [                            ] 0% 0.0s

Does not move forward. Any idea?

**Comment by spencercarli** [comment]
Hey, I apologize for never getting back to you on this. I'm not where the stability of this repo stands with newer versions of Meteor (the example was put together over a year ago) so I'm going to close this.
